### ISSUE TITLE
Custom Decals don't appear on additional cameras

### ISSUE THREAD

**Issue by Kert** [henpemaz/RemixMods#9]
They are actually drawn if you check CustomDecal::DrawSprites but nowhere to be seen for some reason
UPD: More info:
Consider order in which players enter a room with decals from first entry to last:
4 > 3 > 2 > 1 the sprites will show for every camera
1 > 2 > 3 > 4 the sprites will show for camera 1
4 > 1 > 3 > 2 the sprites will show for camera 4, 1
3 > 4 > 2 > 1 the sprites will show for camera 3, 2, 1
1 > 4 > 3 > 2 the sprites will show for camera 1
If there's only one player and 4 split screen is used only camera 1 will show sprites

**Comment by henpemaz** [comment]
Probably some shader shenanigan. I'd need to read the shader source see if
its using anything weird...
